### ISSUE TITLE
Idea for story telling

### ISSUE THREAD

**Issue by anlasne** [epfl-ada/ada-2022-project-rlab#2]
Main idea= How does your child view his possible future through movies?

What we want to show is hoe the representation (ethnicities, age, sexuality) affects the development of children and inspires bias (men are ceos, women are secretaries more attracted to romance Tham carreer, some ethnicities are represented as gang members, how women are pushed to be with older men). 

For example: 
- Show that some children do not see themselves in movies and when they do it is a bad image: like women see themselves as less then, lgbt people do not see a future
- How did it evolve during across time 
Say that these issues impact the development of their children and it should be addressed and evolved more 

- In pornos how during teenage years boys learn that women are objects (paper) and that women should not have pleasure (paper) and how they should be with older guys (data)

**Comment by NicolasRR** [comment]
Generate graphs:
Plots the percentage of male vs female across time for US, Asia, Europe, overall
Percentage of LGBT themed movies across time, overall. Try to analyze by region
Plot age women vs age men across time for porno movies
